.Dd $Mdocdate$
.Dt NAME-OF-UTILITY 1
.Os
.Sh NAME
.Nm name-of-utility
.Nd Short description of the utility.
.Sh SYNOPSIS
.Nm
.Fl h
.Sh DESCRIPTION
Long description of
.Nm .
.Bl -tag -width Ds
.It Fl h
Display brief usage information.
.El
.Sh ENVIRONMENT
Any environment variables affecting the operation of
.Nm .
.\" .Sh FILES
.Sh EXIT STATUS
.Ex -std
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.Sh SEE ALSO
.Xr mdoc 7
.Sh AUTHORS
.An Andreas Kusalananda Kähäri Aq Mt kusalananada.kahari at gmail.com
.\" .Sh CAVEATS
.\" .Sh BUGS
