.Dd $Mdocdate$
.Dt TSH 1
.Os
.Sh Name
.Nm tsh
.Nd Set up a minimal shell envirenment ("test shell").
.Sh SYNOPSIS
.Nm tsh
.Op Fl d
.Op Fl s Ar shell
.Op dir
.Nm tsh
.Fl h
.Sh DESCRIPTION
The
.Nm
utility starts a new shell with minimal environment in a work directory.
.Bl -tag -width Ds
.It Fl d
Delete the work directory when exiting.

This is done using
.Dq rm -rf dir
where
.Dq dir
is the work directory specified on the command line, or the temporary
directory that was created if no directory was specified.

If the HUP (hangup) signal is received, the work
directory will
.Em not
be deleted when exiting.
.It Fl h
Displays brief usage information.
.It Fl s Ar shell
Starts shell
.Dq shell .

The shell is required to be an absolute path listed in
.Dq /etc/shells .

Defaults to
.Dq /bin/sh .
.It Ar dir
Use work directory
.Dq dir .

If
.Dq dir
does not already exist, it will be created.

An empty temporary work directory will be created if no directory is
specified.
.El
.Sh ENVIRONMENT
The environment is cleared and the invoked shell will have
.Ev LC_ALL
set to
.Dq C
by this utility.
.\" .Sh FILES
.Sh EXIT STATUS
.Ex -std
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
