.Dd $Mdocdate$
.Dt TSH 1
.Os
.Sh NAME
.Nm tsh
.Nd Set up a minimal shell environment
.Po
.Qq test shell
.Pc .
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Fl s Ar shell
.Op Ar dir
.Nm tsh
.Fl h
.Sh DESCRIPTION
The
.Nm
utility starts a new shell with minimal environment in a work directory.
The minimal environment will have
.Ev LC_ALL
set to
.Qq C
but will, apart from that, be empty, unless modified by shell
initialization scripts.
.Bl -tag -width Ds
.It Fl d
Delete the work directory when exiting.
.sp
This is done using
.Cm rm Fl rf Ar dir ,
where
.Ar dir
is the work directory specified on the command line, or the temporary
directory that was created if no directory was specified.
.sp
If the USR1 signal is received, the work directory will
.Em not
be deleted when exiting.
.It Fl h
Display brief usage information.
.It Fl s Ar shell
Start shell
.Ar shell .
.sp
The shell is required to be an absolute path listed in
.Pa /etc/shells .
.sp
Defaults to
.Pa /bin/sh .
.It Ar dir
Use work directory
.Ar dir .
.sp
If
.Ar dir
does not already exist, it will be created.
.sp
An empty temporary work directory will be created using
.Cm mktemp Fl d
if no directory is specified.
.El
.Sh EXIT STATUS
.Ex -std
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.Sh SEE ALSO
.Xr mktemp 1
.Sh AUTHORS
.An Andreas Kusalananda Kähäri Aq Mt kusalananada.kahari at gmail.com
.\" .Sh CAVEATS
.\" .Sh BUGS
